apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yjs-rtc-server
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-body-size: 100M
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ .Values.ingress.whitelist }}
spec:
  ingressClassName: public
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: yjs-rtc
                port:
                  number: 4444
      host: {{ .Values.ingress.host }}
  tls:
  - hosts:
    - deep.cs.cityu.edu.hk
    secretName: myingress-cert
status:
  loadBalancer:
    ingress:
      - ip: 127.0.0.1
