apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    service: yjs-rtc
  name: yjs-rtc
spec:
  ports:
    - name: "yjs-rtc-server"
      port: 4444
      targetPort: 4444
  selector:
    service: yjs-rtc
status:
  loadBalancer: {}
